### ISSUE TITLE
Special effect for selecting a potion

### ISSUE THREAD

**Issue by xxc796** [zkcrossteam/zk-2048#12]
The special effect for selecting a potion should be optimized, wait for design

![image](https://github.com/zkcrossteam/g1024/assets/52724558/3df4eb59-27ff-4f20-bf31-38a730461be0)

**Comment by stevending1st** [comment]
![image](https://github.com/zkcrossteam/g1024/assets/23376142/597b7bfa-7f34-4b06-bb80-dc9029505602)

![image](https://github.com/zkcrossteam/g1024/assets/23376142/0be3be19-61e2-43c1-ac0a-e2551c437793)

**Comment by stevending1st** [comment]
![image](https://github.com/zkcrossteam/g1024/assets/23376142/f47a2d22-05cc-40db-95cc-8cf3aa7d7251)

**Comment by stevending1st** [comment]
![image](https://github.com/zkcrossteam/g1024/assets/23376142/0f6a2d72-a6aa-45bd-bb99-f75173591d60)
