### ISSUE TITLE
A walk through tutorial should be added

### ISSUE THREAD

**Issue by xxc796** [zkcrossteam/zk-2048#14]
1. A walk through tutorial should be added according to figma.
2. Judging by device id, when it's the first time for a device to visit the website, the walk through tutorial should be activate.
3. Add a re-trigger button below the control panel, the tutorial should be reactivated by clicking on the button.

![image](https://github.com/zkcrossteam/g1024/assets/52724558/0ad40832-bbf1-475a-800b-b8dea0c9b4ad)

**Comment by wangrunlin** [comment]
https://github.com/zkcrossteam/g1024/blob/76c849357f9c5afa501421c607b188300f2fe588/src/layout/Main.tsx#L73-L76

It has been added now. At present, it is determined whether to display by whether to log in to the account or not.
