### ISSUE TITLE
Add error handler

### ISSUE THREAD

**Issue by glenzk** [zkcrossteam/zk-2048#51]
Add error handler to submit.

If fail with error "Insufficient ZKC token",   show "Insufficient ZKC token, please TopUp ZKC at first!" in the button.

Other failure show "Oops!  Something went wrong." in the buttone

**Comment by steven-zk** [comment]
when show "Oops! Something went wrong." in the button, what will happen when  I click the button?

**Comment by glenzk** [comment]
> when show "Oops! Something went wrong." in the button, what will happen when I click the button?

Just disable the button.
